import SwiftUI
import UIKit

/// Branded share image generated by SwiftUI's ImageRenderer. Lays out the
/// app's kanji-gem identity + this-week stats at a 1080×1920 portrait
/// canvas — same proportions Instagram / TikTok stories expect.
struct ProgressShareView: View {
    let reviewsThisWeek: Int
    let successRate: Double?
    let streak: Int
    let matureCount: Int

    var body: some View {
        ZStack {
            // Backdrop matches the app's washi → sakura gradient.
            LinearGradient(
                colors: [
                    Color(red: 1.000, green: 0.992, blue: 0.973),
                    Color(red: 0.984, green: 0.965, blue: 0.929),
                    Color(red: 0.940, green: 0.860, blue: 0.870).opacity(0.7)
                ],
                startPoint: .top,
                endPoint: .bottom
            )
            .ignoresSafeArea()

            VStack(spacing: 40) {
                Spacer(minLength: 60)

                // Brand header
                VStack(spacing: 12) {
                    KanjiGemBadge(
                        kanji: "漢",
                        tint: Palette.sakura,
                        deeperTint: Color(red: 0.870, green: 0.486, blue: 0.580),
                        size: 140,
                        foreground: Palette.cream
                    )
                    Text("Kanji Crush")
                        .font(.system(size: 40, weight: .bold, design: .rounded))
                        .foregroundStyle(Palette.sumi)
                    Text("This week")
                        .font(.system(size: 22, design: .rounded).weight(.medium))
                        .foregroundStyle(Palette.mist)
                        .textCase(.uppercase)
                        .tracking(2.0)
                }

                // Stat grid
                VStack(spacing: 18) {
                    bigStat(value: "\(reviewsThisWeek)", label: "Reviews", tint: Palette.indigo)
                    bigStat(
                        value: successRate.map { "\(Int(($0 * 100).rounded()))%" } ?? "—",
                        label: "Success rate",
                        tint: Palette.bamboo
                    )
                    HStack(spacing: 18) {
                        smallStat(value: "\(streak)", label: "Day streak", tint: Palette.sakura)
                        smallStat(value: "\(matureCount)", label: "Mature", tint: Palette.gold)
                    }
                }
                .padding(.horizontal, 60)

                Spacer()

                // Footer
                VStack(spacing: 6) {
                    Text("漢字を一つずつ。")
                        .font(.system(size: 26, design: .serif))
                        .foregroundStyle(Palette.sumi.opacity(0.8))
                    Text("One kanji at a time.")
                        .font(.system(size: 18, design: .rounded))
                        .foregroundStyle(Palette.mist)
                        .italic()
                }
                .padding(.bottom, 60)
            }
        }
        .frame(width: 1080, height: 1920)
    }

    private func bigStat(value: String, label: String, tint: Color) -> some View {
        VStack(spacing: 8) {
            Text(value)
                .font(.system(size: 110, weight: .heavy, design: .rounded))
                .foregroundStyle(tint)
            Text(label.uppercased())
                .font(.system(size: 22, design: .rounded).weight(.semibold))
                .foregroundStyle(Palette.sumi)
                .tracking(2.0)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 24)
        .background(tint.opacity(0.10), in: RoundedRectangle(cornerRadius: 28, style: .continuous))
        .overlay(
            RoundedRectangle(cornerRadius: 28, style: .continuous)
                .strokeBorder(tint.opacity(0.4), lineWidth: 2)
        )
    }

    private func smallStat(value: String, label: String, tint: Color) -> some View {
        VStack(spacing: 4) {
            Text(value)
                .font(.system(size: 70, weight: .bold, design: .rounded))
                .foregroundStyle(tint)
            Text(label.uppercased())
                .font(.system(size: 16, design: .rounded).weight(.semibold))
                .foregroundStyle(Palette.sumi)
                .tracking(1.4)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 18)
        .background(tint.opacity(0.10), in: RoundedRectangle(cornerRadius: 22, style: .continuous))
        .overlay(
            RoundedRectangle(cornerRadius: 22, style: .continuous)
                .strokeBorder(tint.opacity(0.4), lineWidth: 2)
        )
    }
}

/// Renders the `ProgressShareView` to a UIImage for the system Share sheet.
@MainActor
enum ProgressShareRenderer {
    static func render(
        reviewsThisWeek: Int,
        successRate: Double?,
        streak: Int,
        matureCount: Int
    ) -> UIImage? {
        let view = ProgressShareView(
            reviewsThisWeek: reviewsThisWeek,
            successRate: successRate,
            streak: streak,
            matureCount: matureCount
        )
        let renderer = ImageRenderer(content: view)
        renderer.scale = 1.0
        renderer.proposedSize = ProposedViewSize(width: 1080, height: 1920)
        return renderer.uiImage
    }
}
